Abstract Factory Pattern in C++
zhenyanghua/design-patterns pull request #1
Opened 2019-09-20 00:41 UTC by daltonkell

Implement the Abstract Factory Pattern example in C++

2019-09-20 12:54 UTC, zhenyanghua requested changes

2019-09-20 12:54 UTC, zhenyanghua commented on AbstractFactoryPatternExample/src/main/cpp/src/abstract_dessert_factory.cpp
> +            break;
Would the `break` be unreachable?

2019-09-20 12:54 UTC, zhenyanghua commented on AbstractFactoryPatternExample/src/main/cpp/src/abstract_dessert_factory.cpp
> +}
It could have a case where there is no default return value, where either an exception needs to be thrown or a null needs to be returned.

2019-09-23 13:34 UTC, daltonkell commented
@zhenyanghua new commit to address your review

2019-09-24 12:54 UTC, zhenyanghua approved these changes

2019-09-24 12:54 UTC, merged